version: "3"

services:
  db:
    image: mysql:latest
    container_name: gameshift-db
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: GameShift
    ports:
      - "3306:3306"
    volumes:
      - gameshift_db:/var/lib/mysql
      - ./Database/GameShift.sql:/docker-entrypoint-initdb.d/GameShift.sql:ro
    networks:
      - gameshift_network
    

  front:
    build:
      context: ./Front_Office
      dockerfile: Dockerfile
    image: younessnb94/gameshift-front:latest
    container_name: gameshift-front
    environment:
      DB_HOST: db:3306
      DB_NAME: GameShift
      DB_USER: root
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - gameshift_network

  back:
    build:
      context: ./Back_Office
      dockerfile: Dockerfile
    image: younessnb94/gameshift-back:latest
    container_name: gameshift-back
    restart: always
    environment:
      DB_HOST: db:3306
      DB_NAME: GameShift
      DB_USER: root
    depends_on:
      - db
    ports:
      - "8081:80"
    networks:
      - gameshift_network

volumes:
  gameshift_db:

networks:
  gameshift_network:
    driver: bridge